package test.dao;

import test.domain.city;

public interface cityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    int insert(city record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    int insertSelective(city record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    city selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    int updateByPrimaryKeySelective(city record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    int updateByPrimaryKey(city record);
}