package test.domain;

public class country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Name
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Continent
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String Continent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Region
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String Region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.SurfaceArea
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Float SurfaceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.IndepYear
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Short IndepYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Population
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Integer Population;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LifeExpectancy
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Float LifeExpectancy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNP
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Float GNP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GNPOld
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Float GNPOld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.LocalName
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String localname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.GovernmentForm
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String governmentform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.HeadOfState
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String headofstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Capital
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private Integer capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Code2
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    private String code2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code
     *
     * @return the value of country.Code
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getCode() {
        return Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code
     *
     * @param Code the value for country.Code
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setCode(String Code) {
        this.Code = Code == null ? null : Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Name
     *
     * @return the value of country.Name
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Name
     *
     * @param name the value for country.Name
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Continent
     *
     * @return the value of country.Continent
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getContinent() {
        return Continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Continent
     *
     * @param Continent the value for country.Continent
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setContinent(String Continent) {
        this.Continent = Continent == null ? null : Continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Region
     *
     * @return the value of country.Region
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getRegion() {
        return Region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Region
     *
     * @param Region the value for country.Region
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setRegion(String Region) {
        this.Region = Region == null ? null : Region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.SurfaceArea
     *
     * @return the value of country.SurfaceArea
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Float getSurfaceArea() {
        return SurfaceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.SurfaceArea
     *
     * @param SurfaceArea the value for country.SurfaceArea
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setSurfaceArea(Float SurfaceArea) {
        this.SurfaceArea = SurfaceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.IndepYear
     *
     * @return the value of country.IndepYear
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Short getIndepYear() {
        return IndepYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.IndepYear
     *
     * @param IndepYear the value for country.IndepYear
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setIndepYear(Short IndepYear) {
        this.IndepYear = IndepYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Population
     *
     * @return the value of country.Population
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Integer getPopulation() {
        return Population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Population
     *
     * @param Population the value for country.Population
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setPopulation(Integer Population) {
        this.Population = Population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LifeExpectancy
     *
     * @return the value of country.LifeExpectancy
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Float getLifeExpectancy() {
        return LifeExpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LifeExpectancy
     *
     * @param LifeExpectancy the value for country.LifeExpectancy
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setLifeExpectancy(Float LifeExpectancy) {
        this.LifeExpectancy = LifeExpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNP
     *
     * @return the value of country.GNP
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Float getGNP() {
        return GNP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNP
     *
     * @param GNP the value for country.GNP
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setGNP(Float GNP) {
        this.GNP = GNP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GNPOld
     *
     * @return the value of country.GNPOld
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Float getGNPOld() {
        return GNPOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GNPOld
     *
     * @param GNPOld the value for country.GNPOld
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setGNPOld(Float GNPOld) {
        this.GNPOld = GNPOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.LocalName
     *
     * @return the value of country.LocalName
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.LocalName
     *
     * @param localname the value for country.LocalName
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setLocalname(String localname) {
        this.localname = localname == null ? null : localname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.GovernmentForm
     *
     * @return the value of country.GovernmentForm
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getGovernmentform() {
        return governmentform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.GovernmentForm
     *
     * @param governmentform the value for country.GovernmentForm
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setGovernmentform(String governmentform) {
        this.governmentform = governmentform == null ? null : governmentform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.HeadOfState
     *
     * @return the value of country.HeadOfState
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getHeadofstate() {
        return headofstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.HeadOfState
     *
     * @param headofstate the value for country.HeadOfState
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setHeadofstate(String headofstate) {
        this.headofstate = headofstate == null ? null : headofstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Capital
     *
     * @return the value of country.Capital
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Capital
     *
     * @param capital the value for country.Capital
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Code2
     *
     * @return the value of country.Code2
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Code2
     *
     * @param code2 the value for country.Code2
     *
     * @mbggenerated Mon Oct 24 23:07:54 CST 2016
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }
}